# Generated by Django 5.1.5 on 2026-02-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_hotel_id_alter_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='is_blocked',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='star_rating',
        ),
        migrations.AddField(
            model_name='hotel',
            name='id_proof1',
            field=models.FileField(blank=True, null=True, upload_to='hotel_docs/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='id_proof2',
            field=models.FileField(blank=True, null=True, upload_to='hotel_docs/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('blocked', 'Blocked')], default='pending', max_length=20),
        ),
    ]
