# Generated by Django 5.1.5 on 2026-02-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_remove_hotel_address_remove_hotel_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('blocked', 'Blocked'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
