# Generated by Django 6.0.2 on 2026-03-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(default='confirm', max_length=20),
        ),
    ]
