# Generated by Django 6.0.2 on 2026-03-02 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='aadhaar_id',
        ),
    ]
