# Generated by Django 6.0.2 on 2026-03-03 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='adults',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='children',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_guests',
        ),
    ]
