# Generated by Django 6.0.2 on 2026-03-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_adults_remove_booking_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adults',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='children',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_guests',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
