# Generated by Django 6.0.2 on 2026-03-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_adults_booking_children_booking_total_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='children',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
