# Generated by Django 6.0.2 on 2026-03-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='children',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
